---
# SPDX-License-Identifier: MPL-2.0
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check freeswitch command works
      ansible.builtin.command: freeswitch -version
      register: command_result
      changed_when: command_result.rc != 0
